### ISSUE TITLE
Video with the robot running the library

### ISSUE THREAD

**Issue by jabrena** [Spartronics4915/SpartronicsLib#2]
Hi,

I was checking the project and it is amazing.
Does exist a video running the library?

**Comment by pietroglyph** [comment]
@jabrena Thanks for your interest in the library! I'm not near a robot right now, so I can't take a video of the V-SLAM or LIDAR capabilities, but [this](https://drive.google.com/open?id=1d2Z03RwUzDNlyQL1N9qxPobRWyqld20R) is a video of the trajectory planning and odometry capabilities. In the video the robot drives away from the origin (under human control), and then returns to the origin using a path it generates on-the-fly.

Let me know if you have any other questions.
